"""The period objects, in the 3D view's Add menu.

Every renderer of the era shipped with the same handful of things to point a
camera at, and comparing your output against somebody else's meant rendering
the same one. They are here under *Add > Halcyon*, generated by `core/geometry`
and arriving with Halcyon materials already on them, so that the first thing a
new user does can be pressing F12 rather than modelling.

The geometry is bpy-free and tested headlessly; this module is only the part
that cannot be -- meshes, materials, operators and the menu.
"""

import bpy
from bpy.props import (BoolProperty, EnumProperty, FloatProperty,
                       FloatVectorProperty, IntProperty, PointerProperty)
from bpy.types import Menu, Operator, Panel, PropertyGroup

from . import templates
from .core import geometry as GEO

ENGINE = 'HALCYON_RENDER'


# ------------------------------------------------------------- scaffolding


def _material(name, color, model='PHONG', **inputs):
    """A Halcyon-shaded material, built rather than looked up.

    Named uniquely per object so adding two teapots does not have the second
    one silently repaint the first.
    """
    mat = bpy.data.materials.new(name)
    from . import compat
    compat.enable_nodes(mat)
    tree = mat.node_tree
    tree.nodes.clear()
    out = tree.nodes.new('ShaderNodeOutputMaterial')
    out.location = (320, 0)
    try:
        shader = tree.nodes.new('HALCYON_ShaderNode')
    except RuntimeError:
        # Halcyon's nodes are not registered -- fall back so the object still
        # arrives with something on it rather than the operator failing
        shader = tree.nodes.new('ShaderNodeBsdfDiffuse')
        shader.location = (0, 0)
        shader.inputs['Color'].default_value = tuple(color)
        tree.links.new(shader.outputs[0], out.inputs['Surface'])
        mat.diffuse_color = tuple(color)
        return mat
    shader.location = (0, 0)
    shader.model = model
    values = dict(inputs)
    values.setdefault('Diffuse Color', tuple(color))
    for key, value in values.items():
        sock = shader.inputs.get(key)
        if sock is None or not hasattr(sock, 'default_value'):
            continue
        try:
            if hasattr(sock.default_value, '__len__'):
                for i in range(min(len(sock.default_value), len(value))):
                    sock.default_value[i] = value[i]
            else:
                sock.default_value = float(value)
        except (TypeError, ValueError):
            pass
    shader.refresh_sockets()
    tree.links.new(shader.outputs['Surface'], out.inputs['Surface'])
    mat.diffuse_color = tuple(color)
    return mat


def _template_material(name, key, fallback):
    mat = bpy.data.materials.new(name)
    ok, _msg = templates.build(mat, key)
    if not ok:
        bpy.data.materials.remove(mat)
        return _material(name, fallback)
    return mat


def _new_object(context, name, verts, faces, materials=(), face_material=None,
                smooth=False, scale=1.0):
    """Build a mesh, wrap it in an object, and hand it to the user selected."""
    mesh = bpy.data.meshes.new(name)
    if scale != 1.0:
        verts = [(x * scale, y * scale, z * scale) for x, y, z in verts]
    mesh.from_pydata(list(verts), [], [list(f) for f in faces])
    mesh.update()
    for mat in materials:
        mesh.materials.append(mat)
    if face_material is not None and len(materials) > 1:
        for poly, index in zip(mesh.polygons, face_material):
            poly.material_index = index
    if smooth:
        for poly in mesh.polygons:
            poly.use_smooth = True

    ob = bpy.data.objects.new(name, mesh)
    return _present_object(context, ob)


def _present_object(context, ob):
    """Link a built object, drop it at the cursor, hand it over selected."""
    collection = context.collection or context.scene.collection
    collection.objects.link(ob)
    cursor = getattr(getattr(context, 'scene', None), 'cursor', None)
    if cursor is not None:
        ob.location = tuple(cursor.location)
    for other in context.selected_objects:
        other.select_set(False)
    ob.select_set(True)
    context.view_layer.objects.active = ob
    return ob


class _AddBase(Operator):
    bl_options = {'REGISTER', 'UNDO'}

    @classmethod
    def poll(cls, context):
        return context.mode == 'OBJECT'


# ------------------------------------------------------------------ teapot


class HALCYON_OT_add_teapot(_AddBase):
    """The Utah teapot, swept from its profile at the resolution you ask for"""

    bl_idname = 'halcyon.add_teapot'
    bl_label = "Utah Teapot"

    steps: IntProperty(
        name="Steps", default=8, min=2, max=32,
        description="Subdivisions along the profile. The whole object is "
                    "generated, so this is a real resolution knob rather than "
                    "a decimation of something fixed")
    segments: IntProperty(name="Segments", default=16, min=4, max=64,
                          description="Subdivisions around the axis")
    size: FloatProperty(name="Size", default=0.5, min=0.001, max=100.0,
                        description="Scale. The teapot is 3.15 units tall "
                                    "before it, as Newell left it")
    smooth: BoolProperty(
        name="Shade Smooth", default=False,
        description="Off by default: faceted is what these looked like, and "
                    "Halcyon's Flat and Gouraud shading rates want the facets")
    material: EnumProperty(
        name="Material", default='CHROME',
        items=(('CHROME', "Chrome", "The one it was always rendered in"),
               ('GOLD', "Gold", ""), ('PLASTIC', "Shiny Plastic", ""),
               ('MARBLE', "Polished Marble", ""), ('NONE', "None", "")))

    def execute(self, context):
        verts, faces = GEO.utah_teapot(self.steps, self.segments)
        mats = ()
        if self.material != 'NONE':
            mats = (_template_material("Teapot", self.material,
                                       (0.75, 0.75, 0.78, 1.0)),)
        _new_object(context, "Teapot", verts, faces, mats,
                    smooth=self.smooth, scale=self.size)
        return {'FINISHED'}


class HALCYON_OT_add_teaset(_AddBase):
    """The rest of Newell's tea service: teapot, cup, saucer and spoon"""

    bl_idname = 'halcyon.add_teaset'
    bl_label = "Newell Teaset"

    steps: IntProperty(name="Steps", default=8, min=2, max=32)
    segments: IntProperty(name="Segments", default=16, min=4, max=64)
    size: FloatProperty(name="Size", default=0.35, min=0.001, max=100.0)
    smooth: BoolProperty(name="Shade Smooth", default=False)

    def execute(self, context):
        china = _material("Teaset China", (0.93, 0.92, 0.90, 1.0),
                          model='BLINN_PHONG', **{'Specular Level': 0.75,
                                                  'Glossiness': 90.0,
                                                  'Fresnel': 0.4})
        builders = {
            'teapot': lambda: GEO.utah_teapot(self.steps, self.segments),
            'teacup': lambda: GEO.teacup(max(self.steps - 2, 2), self.segments),
            'saucer': lambda: GEO.saucer(max(self.steps - 3, 2), self.segments),
            'teaspoon': lambda: GEO.teaspoon(max(self.steps - 2, 2),
                                             max(self.segments // 2, 4)),
        }
        made = []
        for label, key, offset, rel in GEO.TEASET_LAYOUT:
            verts, faces = builders[key]()
            ox, oy, oz = offset
            verts = [(x * rel + ox, y * rel + oy, z * rel + oz)
                     for x, y, z in verts]
            made.append(_new_object(context, label, verts, faces, (china,),
                                    smooth=self.smooth, scale=self.size))
        for ob in made:
            ob.select_set(True)
        if made:
            context.view_layer.objects.active = made[0]
        self.report({'INFO'}, f'{len(made)} objects added')
        return {'FINISHED'}


# ------------------------------------------------------------ Cornell box


class HALCYON_OT_add_cornell_box(_AddBase):
    """The Cornell box at its published dimensions, walls and blocks and all"""

    bl_idname = 'halcyon.add_cornell_box'
    bl_label = "Cornell Box"

    size: FloatProperty(
        name="Size", default=4.0, min=0.01, max=1000.0,
        description="Width of the box. The published measurements are in "
                    "millimetres and are scaled to this")
    emissive: BoolProperty(
        name="Emissive Light Panel", default=True,
        description="Give the ceiling panel a Constant white material. Halcyon "
                    "has no bounce light, so this lights nothing on its own -- "
                    "add an area lamp under it")
    add_lamp: BoolProperty(
        name="Add Area Lamp", default=True,
        description="Put an area lamp at the panel, sized and placed to match "
                    "it, so the box is lit the moment it is added")

    def execute(self, context):
        verts, faces, groups = GEO.cornell_box()
        palette = (
            ('white', (0.73, 0.73, 0.73, 1.0), 'LAMBERT', {}),
            ('red', (0.63, 0.06, 0.05, 1.0), 'LAMBERT', {}),
            ('green', (0.14, 0.45, 0.09, 1.0), 'LAMBERT', {}),
            ('light', (1.0, 0.95, 0.85, 1.0),
             'CONSTANT' if self.emissive else 'LAMBERT',
             {'Self-Illumination': (1.0, 0.95, 0.85, 1.0)}
             if self.emissive else {}),
            ('short', (0.73, 0.73, 0.73, 1.0), 'LAMBERT', {}),
            ('tall', (0.73, 0.73, 0.73, 1.0), 'LAMBERT', {}),
        )
        mats, index = [], {}
        for name, color, model, extra in palette:
            index[name] = len(mats)
            mats.append(_material(f'Cornell {name.title()}', color,
                                  model=model, **extra))
        ob = _new_object(context, "Cornell Box", verts, faces, mats,
                         [index[g] for g in groups], scale=self.size)

        if self.add_lamp:
            lamp_data = bpy.data.lights.new("Cornell Light", 'AREA')
            lamp_data.energy = 100.0 * max(self.size, 0.01) ** 2
            lamp_data.color = (1.0, 0.95, 0.85)
            try:
                lamp_data.shape = 'RECTANGLE'
                lamp_data.size = 0.235 * self.size
                lamp_data.size_y = 0.19 * self.size
            except (AttributeError, TypeError):
                pass
            lamp = bpy.data.objects.new("Cornell Light", lamp_data)
            (context.collection or context.scene.collection).objects.link(lamp)
            # the panel sits at 548.7/552.8 of the box width, just under the
            # ceiling, and the lamp goes a hair below it so it is not co-planar
            lamp.location = (ob.location[0] + 0.0,
                             ob.location[1] + 0.0,
                             ob.location[2] + 0.986 * self.size)
            lamp.rotation_euler = (3.14159265, 0.0, 0.0)
            lamp.parent = ob
            lamp.matrix_parent_inverse = ob.matrix_world.inverted()
        return {'FINISHED'}


# ------------------------------------------------------------ checkerboard


class HALCYON_OT_add_checker_plane(_AddBase):
    """A checkerboard as real alternating faces, not a texture"""

    bl_idname = 'halcyon.add_checker_plane'
    bl_label = "Checker Ground Plane"

    size: FloatProperty(name="Size", default=20.0, min=0.01, max=10000.0)
    divisions: IntProperty(name="Divisions", default=8, min=1, max=256,
                           description="Squares across")
    color_a: FloatVectorProperty(name="Colour A", subtype='COLOR', size=4,
                                 min=0.0, max=1.0,
                                 default=(0.9, 0.9, 0.9, 1.0))
    color_b: FloatVectorProperty(name="Colour B", subtype='COLOR', size=4,
                                 min=0.0, max=1.0,
                                 default=(0.06, 0.06, 0.07, 1.0))
    glossy: BoolProperty(
        name="Reflective", default=False,
        description="Add a reflection amount, for the ray-traced chequerboard "
                    "every renderer's first demo image stood on")

    def execute(self, context):
        verts, faces, groups = GEO.checker_plane(self.size, self.divisions)
        extra = {'Reflection': 0.35, 'Specular Level': 0.7,
                 'Glossiness': 180.0} if self.glossy else {}
        mats = (_material("Checker A", tuple(self.color_a), **extra),
                _material("Checker B", tuple(self.color_b), **extra))
        _new_object(context, "Checker Plane", verts, faces, mats, groups)
        return {'FINISHED'}


# ----------------------------------------------------------- the terrain


def _terrain_material(name, height):
    """R201: the Bryce terrain material, wired to Altitude & Slope.

    The node shipped in an earlier round with nothing to stand on; the
    Terrain operator is what it was built to paint. Factor (height,
    normalised 0..Maximum) drives a colour ramp -- shore grass up
    through rock to snow -- and Slope pulls steep faces toward bare
    rock through a Mix, so cliffs stay stone whatever their altitude.
    All standard nodes plus the two Halcyon ones, fully editable
    afterwards, and the whole chain evaluates identically on the CPU
    and the GPU simulator (both roads already speak every node here).
    """
    mat = bpy.data.materials.new(name)
    from . import compat
    compat.enable_nodes(mat)
    tree = mat.node_tree
    tree.nodes.clear()
    out = tree.nodes.new('ShaderNodeOutputMaterial')
    out.location = (720, 0)
    try:
        shader = tree.nodes.new('HALCYON_ShaderNode')
        alt = tree.nodes.new('HALCYON_AltitudeSlopeNode')
    except RuntimeError:
        # engine nodes unregistered -- a plain matte stand-in so the
        # operator still delivers a mountain rather than an error
        shader = tree.nodes.new('ShaderNodeBsdfDiffuse')
        shader.inputs['Color'].default_value = (0.35, 0.32, 0.28, 1.0)
        tree.links.new(shader.outputs[0], out.inputs['Surface'])
        mat.diffuse_color = (0.35, 0.32, 0.28, 1.0)
        return mat
    shader.location = (480, 0)
    shader.model = 'LAMBERT'
    alt.location = (-260, 0)
    for nm, val in (('Minimum', 0.0), ('Maximum', float(height))):
        s = alt.inputs.get(nm)
        if s is not None:
            s.default_value = val
    ramp = tree.nodes.new('ShaderNodeValToRGB')
    ramp.location = (0, 120)
    cr = ramp.color_ramp
    # four stops: shore grass, dry scrub, bare rock, snowcap
    stops = ((0.0, (0.20, 0.28, 0.12, 1.0)),
             (0.35, (0.36, 0.30, 0.20, 1.0)),
             (0.62, (0.38, 0.36, 0.34, 1.0)),
             (0.85, (0.92, 0.94, 0.97, 1.0)))
    while len(cr.elements) > 1:
        cr.elements.remove(cr.elements[-1])
    cr.elements[0].position = stops[0][0]
    cr.elements[0].color = stops[0][1]
    for pos, col in stops[1:]:
        el = cr.elements.new(pos)
        el.color = col
    mix = tree.nodes.new('ShaderNodeMix')
    mix.location = (260, 40)
    try:
        mix.data_type = 'RGBA'
        mix.clamp_factor = True
    except AttributeError:
        pass

    def _mix_in(nm, ty):
        for s in mix.inputs:
            if s.name == nm and (ty is None or s.type == ty):
                return s
        return None

    rock = _mix_in('B', 'RGBA')
    if rock is not None:
        rock.default_value = (0.33, 0.31, 0.30, 1.0)
    tree.links.new(alt.outputs['Factor'], ramp.inputs['Fac'])
    a_in = _mix_in('A', 'RGBA')
    if a_in is not None:
        tree.links.new(ramp.outputs['Color'], a_in)
    f_in = _mix_in('Factor', 'VALUE')
    if f_in is not None:
        tree.links.new(alt.outputs['Slope'], f_in)
    dc = shader.inputs.get('Diffuse Color')
    if dc is not None:
        res = None
        for s in mix.outputs:
            if s.name == 'Result' and s.type == 'RGBA':
                res = s
                break
        tree.links.new(res if res is not None
                       else mix.outputs[0], dc)
    sl = shader.inputs.get('Specular Level')
    if sl is not None and hasattr(sl, 'default_value'):
        sl.default_value = 0.05
    shader.refresh_sockets()
    tree.links.new(shader.outputs['Surface'], out.inputs['Surface'])
    mat.diffuse_color = (0.38, 0.36, 0.34, 1.0)
    return mat


class HALCYON_OT_add_terrain(_AddBase):
    """A fractal mountain with the Bryce material already on it --
    altitude bands from shore to snow, steep faces pulled to rock"""

    bl_idname = 'halcyon.add_terrain'
    bl_label = "Terrain"

    kind: EnumProperty(
        name="Type", default='MOUNTAIN',
        description="The landform this terrain grows into; every type "
                    "still takes the island, terrace and sea dials",
        items=[
            ('MOUNTAIN', "Mountain",
             "The fractal peak -- rolling fBm blended toward ridged "
             "crests by the Ridged dial"),
            ('HILLS', "Rolling Hills",
             "Soft pastureland, no crests at all"),
            ('CANYON', "Canyon",
             "A high mesa with winding channels carved out of it"),
            ('DUNES', "Dunes",
             "Directional sand waves; the Direction dial turns the "
             "wind that laid them"),
            ('CRATER', "Crater",
             "One great ringed impact: raised rim, sunken floor"),
            ('VOLCANO', "Volcano",
             "The cone with its caldera bitten out of the top"),
            ('PLATEAU', "Plateau",
             "Hard-shouldered table-land, flat on top"),
        ])
    direction: FloatProperty(
        name="Direction", default=0.0, min=-6.2832, max=6.2832,
        subtype='ANGLE',
        description="Turns the Dunes' wind (and is free for any kind "
                    "that later wants a bearing)")
    size: FloatProperty(
        name="Size", default=24.0, min=0.1, max=10000.0,
        description="Width of the terrain grid in scene units")
    divisions: IntProperty(
        name="Divisions", default=96, min=2, max=512,
        description="Grid squares along each side; 96 is a Bryce-era "
                    "mountain, 256 a modern one")
    height: FloatProperty(
        name="Height", default=6.0, min=0.0, max=1000.0,
        description="Peak altitude of the fractal at full strength")
    feature_scale: FloatProperty(
        name="Feature Scale", default=10.0, min=0.1, max=1000.0,
        description="Metres per large noise feature -- bigger numbers "
                    "mean broader, calmer mountains")
    octaves: IntProperty(
        name="Detail", default=6, min=1, max=12,
        description="Fractal detail levels; each adds finer bumps at "
                    "half the strength set by Roughness")
    roughness: FloatProperty(
        name="Roughness", default=0.5, min=0.05, max=0.95,
        description="How much each finer detail level contributes -- "
                    "low is rolling hills, high is crumpled rock")
    ridge: FloatProperty(
        name="Ridged", default=0.5, min=0.0, max=1.0,
        description="Blend from smooth rolling fBm (0) to the "
                    "knife-edged ridged crests Bryce is remembered "
                    "for (1)")
    island: FloatProperty(
        name="Island Falloff", default=0.4, min=0.0, max=1.0,
        description="Fades the height to zero toward the grid edge so "
                    "the mountain ends inside the grid instead of "
                    "slicing off at the boundary; 0 disables")
    terraces: IntProperty(
        name="Terraces", default=0, min=0, max=64,
        description="Above zero, quantises the height into this many "
                    "shelves with smoothed risers -- Bryce's "
                    "terracing; 0 is off")
    sea_level: FloatProperty(
        name="Sea Level", default=0.0, min=0.0, max=0.95,
        description="Flattens everything below this fraction of the "
                    "height into a floor -- the water table an ocean "
                    "plane sits on; 0 is off")
    seed: IntProperty(
        name="Seed", default=0, min=0, max=100000,
        description="Re-deals the mountain; the same seed builds the "
                    "same mountain on every machine")
    smooth: BoolProperty(
        name="Smooth Shading", default=True,
        description="Smooth-shade the grid so slopes grade instead of "
                    "facet; turn off for the flat-shaded early look")

    def execute(self, context):
        verts, faces = GEO.terrain(
            self.size, self.divisions, self.height, self.feature_scale,
            self.octaves, self.roughness, self.ridge, self.island,
            self.terraces, self.sea_level, self.seed,
            kind=self.kind, direction=self.direction)
        label = self.kind.title().replace('_', ' ')
        mat = _terrain_material(label, max(float(self.height), 1e-3))
        _new_object(context, label, verts, faces, (mat,),
                    smooth=self.smooth)
        return {'FINISHED'}


# ---------------------------------------------------------------- fur


def _fur_material(name, density, root_color, tip_color):
    """The classic shell-fur graph, wired from real nodes.

    Hair Info ▸ Intercept feeds two chains: a ColorRamp grades root to
    tip colour, and a Math ▸ Greater Than tests the Fur Tufts field
    against the shell height. Fur Tufts is the texture shell fur
    actually reads (R209): ROUND strand cross-sections whose height
    peaks at each tuft's centre, so every shell up the stack keeps a
    smaller disc and the tufts taper into strand tips -- not the square
    same-width columns a flat per-cell hash gave. The material is
    marked Hair Geometry so Hair Info reads the shells' colour layer.
    """
    mat = bpy.data.materials.new(name)
    from . import compat
    compat.enable_nodes(mat)
    tree = mat.node_tree
    tree.nodes.clear()
    out = tree.nodes.new('ShaderNodeOutputMaterial')
    out.location = (620, 0)
    shader = tree.nodes.new('HALCYON_ShaderNode')
    shader.location = (330, 0)
    try:
        shader.model = 'OREN_NAYAR'
    except Exception:                                           # noqa: BLE001
        pass
    hair = tree.nodes.new('ShaderNodeHairInfo')
    hair.location = (-380, 60)
    ramp = tree.nodes.new('ShaderNodeValToRGB')
    ramp.location = (-120, 180)
    try:
        el = ramp.color_ramp.elements
        el[0].position = 0.0
        el[0].color = tuple(root_color) + (1.0,)
        el[1].position = 1.0
        el[1].color = tuple(tip_color) + (1.0,)
    except Exception:                                           # noqa: BLE001
        pass
    tuft = tree.nodes.new('HALCYON_FurTuftsNode')
    tuft.location = (-380, -220)
    try:
        tuft.inputs['Scale'].default_value = float(density)
    except Exception:                                           # noqa: BLE001
        pass
    # the tuft pattern MUST be sampled in UV space: every shell copies
    # the base mesh's UVs, so the same tuft lands on the same spot of
    # every shell and the stack reads as standing fur. Generated
    # coordinates differ per shell (they are inflated copies) and the
    # tufts would shear apart.
    texco = tree.nodes.new('ShaderNodeTexCoord')
    texco.location = (-620, -220)
    gt = tree.nodes.new('ShaderNodeMath')
    gt.location = (-120, -160)
    gt.operation = 'GREATER_THAN'
    links = tree.links
    links.new(hair.outputs['Intercept'], ramp.inputs['Fac'])
    links.new(ramp.outputs['Color'], shader.inputs['Diffuse Color'])
    try:
        links.new(texco.outputs['UV'], tuft.inputs['Vector'])
    except Exception:                                           # noqa: BLE001
        pass
    ht_out = tuft.outputs.get('Height') or tuft.outputs[-1]
    links.new(ht_out, gt.inputs[0])
    links.new(hair.outputs['Intercept'], gt.inputs[1])
    links.new(gt.outputs['Value'], shader.inputs['Opacity'])
    links.new(shader.outputs['Surface'], out.inputs['Surface'])
    try:
        mat.halcyon.strand = True
        # shells over shells over the base coat would blanket the body
        # in its own cast shadow (shadow rays see geometry, not the
        # alpha-tested tufts) -- the era's shell fur cast none either
        mat.halcyon.cast_shadow = False
        # R211: hard tuft alpha is PUNCH-THROUGH -- it resolves in the
        # z-buffer and shades once, never as sorted blend layers. This
        # is the whole difference between fur that renders at opaque
        # speed and fur that drowns the frame in layer compositing
        mat.halcyon.alpha_mode = 'CLIP'
    except Exception:                                           # noqa: BLE001
        pass
    mat.diffuse_color = tuple(root_color) + (1.0,)
    return mat


class HALCYON_OT_add_fur_shells(_AddBase):
    """Grow shell fur on the active mesh -- the era's other hair:
    stacked inflated copies wearing alpha-tested tufts, the Dreamcast
    and GameCube fur look. Uses the Hair Info node's strand convention,
    so the auto-built material is an ordinary node graph you can edit"""

    bl_idname = 'halcyon.add_fur_shells'
    bl_label = "Fur Shells (from Active)"

    shells: IntProperty(
        name="Shells", default=16, min=2, max=64,
        description="How many stacked copies build the pelt; the era "
                    "ran 8 to 16 -- more layers slice each tuft's taper "
                    "finer, and cost fill")
    length: FloatProperty(
        name="Length", default=0.25, min=0.001, max=100.0,
        description="Fur length in scene units, root surface to the "
                    "outermost shell")
    curve: FloatProperty(
        name="Packing", default=1.0, min=0.25, max=4.0,
        description="Shell spacing bias -- above 1 packs the shells "
                    "toward the root where fur is densest")
    density: FloatProperty(
        name="Tuft Density", default=48.0, min=1.0, max=512.0,
        description="Strand cross-sections per UV unit -- the Fur "
                    "Tufts texture's Scale; higher is finer, denser "
                    "fur")
    comb: FloatVectorProperty(
        name="Comb", default=(0.0, 0.0, -0.05), subtype='TRANSLATION',
        description="World-space lean the shells droop into "
                    "quadratically -- gravity, or a parting")
    root_color: FloatVectorProperty(
        name="Root Colour", subtype='COLOR', size=3, min=0.0, max=1.0,
        default=(0.16, 0.10, 0.06),
        description="Fur colour at the skin, usually the darker end")
    tip_color: FloatVectorProperty(
        name="Tip Colour", subtype='COLOR', size=3, min=0.0, max=1.0,
        default=(0.65, 0.48, 0.28),
        description="Fur colour at the tips, catching the light")

    @classmethod
    def poll(cls, context):
        ob = getattr(context, 'active_object', None)
        return (context.mode == 'OBJECT' and ob is not None
                and getattr(ob, 'type', '') == 'MESH')

    def execute(self, context):
        src = context.active_object
        mat = _fur_material(f"{src.name} Fur", self.density,
                            tuple(self.root_color),
                            tuple(self.tip_color))
        ob, warn = _fur_realize(context, src,
                                dict(shells=int(self.shells),
                                     length=float(self.length),
                                     curve=float(self.curve),
                                     comb=tuple(self.comb)), mat=mat)
        if ob is None:
            self.report({'ERROR'}, warn or 'the fur mesh failed to build')
            return {'CANCELLED'}
        if warn:
            self.report({'WARNING'}, warn)
        # hand the pelt its live settings: the same dials, editable in
        # Object Properties from now on (R211)
        fs = getattr(ob, 'halcyon_fur', None)
        if fs is not None:
            global _FUR_BUSY
            _FUR_BUSY = True
            try:
                fs.is_fur = True
                fs.source = src
                fs.shells = int(self.shells)
                fs.length = float(self.length)
                fs.curve = float(self.curve)
                fs.density = float(self.density)
                fs.comb = tuple(self.comb)
                fs.root_color = tuple(self.root_color)
                fs.tip_color = tuple(self.tip_color)
            finally:
                _FUR_BUSY = False
        return {'FINISHED'}


# ------------------------------------------- live fur settings (R211)
#
# "The settings for the shell (layers, length, etc) should be in the
# object's Object Properties for easy editing and changing." They are:
# the Add operator stores its dials on the object, a panel in Object
# Properties edits them, and every edit re-grows the shells through the
# SAME builder the operator used -- one road, no drift.


def _read_source_mesh(src):
    """verts / normals / tris / first-seen per-vertex UVs off a mesh
    object, numpy-fast -- the exporter-shaped arrays fur_shells eats."""
    import numpy as np
    me = src.data
    me.calc_loop_triangles()
    nv = len(me.vertices)
    verts = np.empty(nv * 3, np.float32)
    me.vertices.foreach_get('co', verts)
    normals = np.empty(nv * 3, np.float32)
    me.vertices.foreach_get('normal', normals)
    tris = np.empty(len(me.loop_triangles) * 3, np.int32)
    me.loop_triangles.foreach_get('vertices', tris)
    uvs = None
    if me.uv_layers.active is not None:
        uvs = np.zeros((nv, 2), np.float32)
        seen = np.zeros(nv, bool)
        layer = me.uv_layers.active.data
        for loop in me.loops:
            vi = loop.vertex_index
            if not seen[vi]:
                uvs[vi] = layer[loop.index].uv[:]
                seen[vi] = True
    return (verts.reshape(-1, 3), normals.reshape(-1, 3),
            tris.reshape(-1, 3), uvs)


def _fur_shell_mesh(name, sv, st_, materials):
    """A shell mesh datablock on the ONE proven road, then VERIFIED.

    R214: 1.55.0 built this by hand (vertices.add + loop offsets via
    foreach_set) for slider speed, and on real Blender that road
    produced a corrupt mesh the stub suite could never see -- the field
    rendered a black pelt for it. Every other Halcyon object has always
    built through from_pydata, so the fur does too, and then the
    triangles are READ BACK and compared to what was asked for: a build
    that cannot prove its own connectivity raises instead of shipping.
    Returns (mesh, problem_or_None)."""
    import numpy as np
    mesh = bpy.data.meshes.new(name)
    mesh.from_pydata([tuple(v) for v in sv], [], [tuple(t) for t in st_])
    mesh.update()
    problem = None
    try:
        mesh.calc_loop_triangles()
        nv = len(mesh.vertices)
        nt = len(mesh.loop_triangles)
        if nv != len(sv) or nt != len(st_):
            problem = (f'the mesh built {nv} vertices / {nt} triangles '
                       f'where {len(sv)} / {len(st_)} were asked for')
        else:
            back = np.empty(nt * 3, np.int32)
            mesh.loop_triangles.foreach_get('vertices', back)
            if not np.array_equal(back.reshape(-1, 3),
                                  np.asarray(st_, np.int32)):
                problem = ('the mesh connectivity read back differently '
                           'than it was written')
    except Exception:                                           # noqa: BLE001
        # a stub bpy (the test suite) may not carry loop_triangles;
        # real Blender always does, and real Blender is where the
        # verification matters
        problem = None
    for m in materials:
        if m is not None:
            mesh.materials.append(m)
    try:
        import numpy as _np
        mesh.polygons.foreach_set(
            'use_smooth', _np.ones(len(mesh.polygons), bool))
    except Exception:                                           # noqa: BLE001
        for poly in mesh.polygons:
            poly.use_smooth = True
    return mesh, problem


def _apply_fur_layers(mesh, sc, suv, has_uv):
    """The strand colour layer and the copied UVs; returns a warning
    string when the colour layer could not be written -- and READS THE
    LAYER BACK (R214): a colour layer that silently zeroes is exactly a
    black pelt with every shell dense (intercept 0 passes every alpha
    test and wears the root colour), which is what the field got."""
    import numpy as np
    warn = None
    try:
        attr = mesh.color_attributes.new(name='HalcyonFur',
                                         type='FLOAT_COLOR',
                                         domain='POINT')
        attr.data.foreach_set('color', sc.reshape(-1))
        try:
            mesh.color_attributes.render_color_index = 0
            mesh.color_attributes.active_color_index = 0
        except Exception:                                       # noqa: BLE001
            pass
        try:
            back = np.zeros(int(sc.size), np.float32)
            attr.data.foreach_get('color', back)
            if not np.allclose(back, np.asarray(sc, np.float32).ravel(),
                               atol=1e-5):
                warn = ('the fur colour layer failed its read-back '
                        'verification; Hair Info would read wrong '
                        'strand data')
        except Exception:                                       # noqa: BLE001
            pass  # a stub bpy; real Blender verifies
    except Exception:                                           # noqa: BLE001
        warn = ("could not write the fur colour layer; the Hair Info "
                "node will read zeros")
    # (UV layers are copied loop-exactly by _copy_uv_layers now -- the
    # old first-seen-per-vertex write smeared every seam)
    return warn


# ------------------------------------------- the pelt wears its source (R215)
#
# "The fur shells don't copy vertex groups, vertex colors, modifiers,
# shape-keys, etc. When they should." They should: a pelt that cannot
# follow its body is a prop. Everything below tiles the source's
# per-vertex data across the shell stack (shell k vertex = k*nv + v),
# and remaps per-corner data through the triangulation
# (pelt loop (k, t, c) = source loop_triangles[t].loops[c]).

#: modifiers that change the vertex count or topology cannot ride the
#: pelt -- its strand colour layer is baked per vertex. Everything that
#: only MOVES vertices (or edits weights) copies across; an Armature
#: with the copied vertex groups is what makes fur follow a rig.
_FUR_MOD_SKIP = frozenset({
    'ARRAY', 'BEVEL', 'BOOLEAN', 'BUILD', 'DECIMATE', 'EDGE_SPLIT',
    'MASK', 'MIRROR', 'MULTIRES', 'REMESH', 'SCREW', 'SKIN', 'SOLIDIFY',
    'SUBSURF', 'TRIANGULATE', 'VOLUME_TO_MESH', 'WELD', 'WIREFRAME',
    'NODES', 'EXPLODE', 'OCEAN', 'PARTICLE_INSTANCE', 'PARTICLE_SYSTEM',
    'FLUID'})


def _copy_uv_layers(mesh, src_me, count, lt_loops):
    """EVERY source UV layer, exactly. The old road copied one layer by
    first-seen-per-vertex, which smeared every UV seam; the pelt loop
    (shell k, tri t, corner c) corresponds to source loop
    loop_triangles[t].loops[c], so the copy can be loop-exact."""
    import numpy as np
    made = 0
    try:
        active = src_me.uv_layers.active
        for layer in src_me.uv_layers:
            data = np.empty(len(src_me.loops) * 2, np.float32)
            layer.data.foreach_get('uv', data)
            per_shell = data.reshape(-1, 2)[lt_loops]
            nl = mesh.uv_layers.new(name=layer.name)
            nl.data.foreach_set(
                'uv', np.tile(per_shell, (count, 1)).ravel())
            if active is not None and layer.name == active.name:
                try:
                    mesh.uv_layers.active = nl
                except Exception:                               # noqa: BLE001
                    pass
            made += 1
    except Exception:                                           # noqa: BLE001
        pass
    return made


def _copy_color_attributes(mesh, src_me, count, lt_loops):
    """The source's own colour layers ride along (point domain tiled by
    vertex, corner domain remapped through the triangulation), so
    Vertex Color and Attribute nodes keep painting the pelt.
    'HalcyonFur' stays the strand layer and is never shadowed."""
    import numpy as np
    made = 0
    try:
        for a in (getattr(src_me, 'color_attributes', None) or ()):
            if a.name == 'HalcyonFur':
                continue
            if a.domain == 'POINT':
                data = np.empty(len(src_me.vertices) * 4, np.float32)
                a.data.foreach_get('color', data)
                out = np.tile(data.reshape(-1, 4), (count, 1))
            elif a.domain == 'CORNER':
                data = np.empty(len(src_me.loops) * 4, np.float32)
                a.data.foreach_get('color', data)
                out = np.tile(data.reshape(-1, 4)[lt_loops], (count, 1))
            else:
                continue
            try:
                na = mesh.color_attributes.new(
                    name=a.name, type='FLOAT_COLOR', domain=a.domain)
                na.data.foreach_set('color', out.ravel())
                made += 1
            except Exception:                                   # noqa: BLE001
                pass
    except Exception:                                           # noqa: BLE001
        pass
    return made


def _copy_vertex_groups(ob, src, count, nv):
    """Every source vertex group, weights tiled across the shells --
    with these in place, a copied Armature modifier deforms the pelt
    exactly as it deforms the skin."""
    made = 0
    try:
        weights = {g.index: [] for g in src.vertex_groups}
        if not weights:
            return 0
        for v in src.data.vertices:
            for ge in v.groups:
                if ge.weight > 0.0 and ge.group in weights:
                    weights[ge.group].append((v.index, ge.weight))
        for g in src.vertex_groups:
            vg = ob.vertex_groups.new(name=g.name)
            for vi, w in weights.get(g.index, ()):
                vg.add([k * nv + vi for k in range(count)], w,
                       'REPLACE')
            made += 1
    except Exception:                                           # noqa: BLE001
        pass
    return made


def _copy_shape_keys(ob, src, count, nv, base_co):
    """Source shape keys, re-grown on the stack: every shell vertex
    moves by its base vertex's key delta. First-order follow -- the
    shells translate with the surface rather than re-deriving their
    normals, which is how the era's fur rode a morphing face. Key
    values and slider ranges copy; drivers are yours to re-point."""
    import numpy as np
    made = 0
    try:
        kb_src = getattr(getattr(src.data, 'shape_keys', None),
                         'key_blocks', None)
        if not kb_src or len(kb_src) < 2:
            return 0
        b = np.empty(nv * 3, np.float32)
        kb_src[0].data.foreach_get('co', b)
        b = b.reshape(-1, 3)
        ob.shape_key_add(name=kb_src[0].name, from_mix=False)
        pelt = np.asarray(base_co, np.float32)
        for kb in kb_src[1:]:
            c = np.empty(nv * 3, np.float32)
            kb.data.foreach_get('co', c)
            delta = c.reshape(-1, 3) - b
            sk = ob.shape_key_add(name=kb.name, from_mix=False)
            sk.data.foreach_set(
                'co', (pelt + np.tile(delta, (count, 1))).ravel())
            try:
                sk.slider_min = kb.slider_min
                sk.slider_max = kb.slider_max
                sk.value = kb.value
            except Exception:                                   # noqa: BLE001
                pass
            made += 1
    except Exception:                                           # noqa: BLE001
        pass
    return made


def _copy_modifiers(ob, src):
    """Deforming modifiers ride the pelt -- Armature above all.
    Anything that changes the vertex count is skipped BY NAME, because
    the strand colour layer is baked per vertex."""
    copied, skipped = [], []
    try:
        for mod in src.modifiers:
            if mod.type in _FUR_MOD_SKIP:
                skipped.append(f'{mod.name} ({mod.type})')
                continue
            try:
                new = ob.modifiers.new(mod.name, mod.type)
                if new is None:
                    skipped.append(f'{mod.name} ({mod.type})')
                    continue
                for pr in mod.bl_rna.properties:
                    ident = pr.identifier
                    if getattr(pr, 'is_readonly', False) or \
                            ident in ('type', 'name'):
                        continue
                    try:
                        setattr(new, ident, getattr(mod, ident))
                    except Exception:                           # noqa: BLE001
                        pass
                copied.append(mod.name)
            except Exception:                                   # noqa: BLE001
                skipped.append(getattr(mod, 'name', '?'))
    except Exception:                                           # noqa: BLE001
        pass
    return copied, skipped


def _dress_from_source(ob, mesh, src, count, base_co):
    """Everything of the source's that the pelt should keep wearing.

    Re-run whole on every rebuild: the pelt is DERIVED, so its groups,
    keys and modifiers are cleared and re-copied from the source --
    hand-added ones belong on the source, where the pelt inherits them.
    Returns console notes (skipped modifiers, by name)."""
    import numpy as np
    notes = []
    src_me = src.data
    nv = len(src_me.vertices)
    try:
        src_me.calc_loop_triangles()
        lt = np.empty(len(src_me.loop_triangles) * 3, np.int32)
        src_me.loop_triangles.foreach_get('loops', lt)
    except Exception:                                           # noqa: BLE001
        lt = None
    if lt is not None:
        _copy_uv_layers(mesh, src_me, count, lt)
        _copy_color_attributes(mesh, src_me, count, lt)
    try:
        ob.vertex_groups.clear()
    except Exception:                                           # noqa: BLE001
        pass
    try:
        for m in list(ob.modifiers):
            ob.modifiers.remove(m)
    except Exception:                                           # noqa: BLE001
        pass
    _copy_vertex_groups(ob, src, count, nv)
    _copy_shape_keys(ob, src, count, nv, base_co)
    _copied, skipped = _copy_modifiers(ob, src)
    if skipped:
        notes.append('modifiers not copied (they change the vertex '
                     'count the strand layer is baked for): '
                     + ', '.join(skipped))
    try:
        # the pelt belongs to its body: follow object-level animation
        ob.parent = src
        ob.matrix_world = src.matrix_world.copy()
    except Exception:                                           # noqa: BLE001
        pass
    return notes


def _fur_realize(context, src, params, ob=None, mat=None):
    """Grow (ob None) or re-grow (ob given) a fur-shell object from its
    source mesh. One builder for the operator AND the live panel."""
    verts, normals, tris, uvs = _read_source_mesh(src)
    sv, st_, _sn, suv, sc = GEO.fur_shells(
        verts, normals, tris, count=int(params['shells']),
        length=float(params['length']), curve=float(params['curve']),
        comb=tuple(params['comb']), uvs=uvs)
    if ob is None:
        mats = (mat,) if mat is not None else ()
        name = f"{src.name} Fur Shells"
    else:
        mats = tuple(ob.data.materials)
        name = ob.data.name
    mesh, problem = _fur_shell_mesh(name, sv, st_, mats)
    warn = _apply_fur_layers(mesh, sc, suv, uvs is not None)
    if problem is not None or (warn and 'verification' in warn):
        # R214: a build that fails its own read-back NEVER replaces a
        # working pelt or ships silently -- the field wore a black fur
        # ball for a corrupt build that was only checked by counting
        why = problem or warn
        try:
            bpy.data.meshes.remove(mesh)
        except Exception:                                       # noqa: BLE001
            pass
        if ob is not None:
            return ob, (f'the rebuilt mesh failed verification '
                        f'({why}); the existing pelt is untouched')
        return None, f'the fur mesh failed verification ({why})'
    if ob is None:
        ob = bpy.data.objects.new(f"{src.name} Fur Shells", mesh)
        _present_object(context, ob)
    else:
        old = ob.data
        old_name = old.name
        ob.data = mesh
        try:
            if old.users == 0:
                bpy.data.meshes.remove(old)
                mesh.name = old_name
        except Exception:                                       # noqa: BLE001
            pass
    # R215: the pelt wears its source -- UV layers (loop-exact), colour
    # layers, vertex groups, shape keys, deforming modifiers, parenting
    for note in _dress_from_source(ob, mesh, src, int(params['shells']),
                                   sv):
        print(f'[Halcyon] fur: {note}')
    try:
        ob.matrix_world = src.matrix_world.copy()
    except Exception:                                           # noqa: BLE001
        pass
    return ob, warn


def _fur_retune_material(ob, density, root, tip):
    """Push density and colours into the pelt's own fur material --
    node edits, no rebuild needed."""
    mat = None
    for m in list(getattr(ob.data, 'materials', []) or []):
        if m is not None and getattr(getattr(m, 'halcyon', None),
                                     'strand', False):
            mat = m
            break
    if mat is None or getattr(mat, 'node_tree', None) is None:
        return
    try:
        # R219: re-assert the era flags on every retune/rebuild, so
        # Rebuild From Source is the one cure the health warnings can
        # always name. Shell fur casts NO shadow (a pelt that casts
        # blankets its own lower layers and the body -- the black-pelt
        # field report) and wears punch-through alpha, both period-
        # correct and both cheap.
        mat.halcyon.cast_shadow = False
        mat.halcyon.alpha_mode = 'CLIP'
    except Exception:                                           # noqa: BLE001
        pass
    for nd in mat.node_tree.nodes:
        bid = getattr(nd, 'bl_idname', '')
        if bid == 'HALCYON_FurTuftsNode':
            try:
                nd.inputs['Scale'].default_value = float(density)
            except Exception:                                   # noqa: BLE001
                pass
        elif bid == 'ShaderNodeValToRGB':
            try:
                el = nd.color_ramp.elements
                el[0].color = tuple(root) + (1.0,)
                el[-1].color = tuple(tip) + (1.0,)
            except Exception:                                   # noqa: BLE001
                pass
    try:
        mat.diffuse_color = tuple(root) + (1.0,)
    except Exception:                                           # noqa: BLE001
        pass


#: re-entrancy guard: the operator filling the panel's fields, and the
#: rebuild itself, must not re-trigger the update callbacks
_FUR_BUSY = False


def _fur_geo_update(self, context):
    global _FUR_BUSY
    if _FUR_BUSY or not self.is_fur:
        return
    ob = self.id_data
    src = self.source
    if src is None or getattr(src, 'type', '') != 'MESH' or src is ob:
        return
    _FUR_BUSY = True
    try:
        _ob, warn = _fur_realize(
            context, src,
            dict(shells=self.shells, length=self.length,
                 curve=self.curve, comb=tuple(self.comb)), ob=ob)
        if warn:
            print(f'[Halcyon] fur: {warn}')
    except Exception:                                           # noqa: BLE001
        import traceback
        traceback.print_exc()
    finally:
        _FUR_BUSY = False


def _fur_mat_update(self, context):
    global _FUR_BUSY
    if _FUR_BUSY or not self.is_fur:
        return
    _FUR_BUSY = True
    try:
        _fur_retune_material(self.id_data, self.density,
                             tuple(self.root_color),
                             tuple(self.tip_color))
    except Exception:                                           # noqa: BLE001
        import traceback
        traceback.print_exc()
    finally:
        _FUR_BUSY = False


class HalcyonFurSettings(PropertyGroup):
    """The fur-shell dials, living on the pelt object itself."""

    is_fur: BoolProperty(default=False, options={'HIDDEN'})
    source: PointerProperty(
        type=bpy.types.Object, name="Source",
        poll=lambda self, ob: getattr(ob, 'type', '') == 'MESH',
        update=_fur_geo_update,
        description="The mesh the shells grow from. Edit it, then "
                    "Rebuild From Source to re-grow the pelt on the "
                    "new shape")
    shells: IntProperty(
        name="Shells", default=16, min=2, max=64,
        update=_fur_geo_update,
        description="How many stacked copies build the pelt; the era "
                    "ran 8 to 16 -- more layers slice each tuft's "
                    "taper finer, and cost fill")
    length: FloatProperty(
        name="Length", default=0.25, min=0.001, max=100.0,
        update=_fur_geo_update,
        description="Fur length in scene units, root surface to the "
                    "outermost shell")
    curve: FloatProperty(
        name="Packing", default=1.0, min=0.25, max=4.0,
        update=_fur_geo_update,
        description="Shell spacing bias -- above 1 packs the shells "
                    "toward the root where fur is densest")
    comb: FloatVectorProperty(
        name="Comb", default=(0.0, 0.0, -0.05), subtype='TRANSLATION',
        update=_fur_geo_update,
        description="World-space lean the shells droop into "
                    "quadratically -- gravity, or a parting")
    density: FloatProperty(
        name="Tuft Density", default=48.0, min=1.0, max=512.0,
        update=_fur_mat_update,
        description="Strand cross-sections per UV unit -- the Fur "
                    "Tufts texture's Scale; higher is finer, denser "
                    "fur")
    root_color: FloatVectorProperty(
        name="Root Colour", subtype='COLOR', size=3, min=0.0, max=1.0,
        default=(0.16, 0.10, 0.06), update=_fur_mat_update,
        description="Fur colour at the skin, usually the darker end")
    tip_color: FloatVectorProperty(
        name="Tip Colour", subtype='COLOR', size=3, min=0.0, max=1.0,
        default=(0.65, 0.48, 0.28), update=_fur_mat_update,
        description="Fur colour at the tips, catching the light")


class HALCYON_OT_fur_rebuild(Operator):
    """Re-grow the shells from the source mesh as it is NOW -- picking
    up sculpts, edits and new UVs the live dials cannot see"""

    bl_idname = 'halcyon.fur_rebuild'
    bl_label = "Rebuild From Source"
    bl_options = {'REGISTER', 'UNDO'}

    @classmethod
    def poll(cls, context):
        ob = getattr(context, 'object', None)
        return (ob is not None
                and getattr(getattr(ob, 'halcyon_fur', None),
                            'is_fur', False))

    def execute(self, context):
        global _FUR_BUSY
        ob = context.object
        fs = ob.halcyon_fur
        src = fs.source
        if src is None or getattr(src, 'type', '') != 'MESH':
            self.report({'WARNING'}, "the fur has no source mesh -- "
                                     "pick one in the panel")
            return {'CANCELLED'}
        _FUR_BUSY = True
        try:
            _ob, warn = _fur_realize(
                context, src,
                dict(shells=fs.shells, length=fs.length,
                     curve=fs.curve, comb=tuple(fs.comb)), ob=ob)
            _fur_retune_material(ob, fs.density, tuple(fs.root_color),
                                 tuple(fs.tip_color))
        finally:
            _FUR_BUSY = False
        if warn:
            self.report({'ERROR'} if 'verification' in warn
                        else {'WARNING'}, warn)
        return {'FINISHED'}


class HALCYON_PT_fur(Panel):
    """Object Properties > Halcyon Fur: the pelt's live dials."""

    bl_label = "Halcyon Fur"
    bl_idname = 'HALCYON_PT_fur'
    bl_space_type = 'PROPERTIES'
    bl_region_type = 'WINDOW'
    bl_context = 'object'

    @classmethod
    def poll(cls, context):
        ob = getattr(context, 'object', None)
        return (ob is not None
                and getattr(getattr(ob, 'halcyon_fur', None),
                            'is_fur', False))

    def draw(self, context):
        layout = self.layout
        layout.use_property_split = True
        fs = context.object.halcyon_fur
        layout.prop(fs, 'source')
        src = fs.source
        if src is None or getattr(src, 'type', '') != 'MESH':
            layout.label(text="No source mesh -- the dials cannot "
                              "re-grow the pelt", icon='ERROR')
        col = layout.column(align=True)
        col.prop(fs, 'shells')
        col.prop(fs, 'length')
        col.prop(fs, 'curve')
        col.prop(fs, 'comb')
        col = layout.column(align=True)
        col.prop(fs, 'density')
        col.prop(fs, 'root_color')
        col.prop(fs, 'tip_color')
        layout.operator(HALCYON_OT_fur_rebuild.bl_idname,
                        icon='FILE_REFRESH')


# -------------------------------------------------------------- the menu


class VIEW3D_MT_halcyon_add(Menu):
    bl_idname = 'VIEW3D_MT_halcyon_add'
    bl_label = "Halcyon"

    def draw(self, context):
        layout = self.layout
        layout.operator(HALCYON_OT_add_teapot.bl_idname, icon='MESH_MONKEY')
        layout.operator(HALCYON_OT_add_teaset.bl_idname, icon='OUTLINER_OB_MESH')
        layout.separator()
        layout.operator(HALCYON_OT_add_cornell_box.bl_idname, icon='MESH_CUBE')
        layout.operator(HALCYON_OT_add_checker_plane.bl_idname,
                        icon='MESH_GRID')
        layout.separator()
        layout.operator(HALCYON_OT_add_terrain.bl_idname,
                        icon='RNDCURVE')
        layout.operator(HALCYON_OT_add_fur_shells.bl_idname,
                        icon='STRANDS')


def draw_add_menu(self, context):
    if getattr(context, 'engine', None) != ENGINE:
        return
    self.layout.separator()
    self.layout.menu(VIEW3D_MT_halcyon_add.bl_idname, icon='SHADING_RENDERED')


CLASSES = (HalcyonFurSettings, HALCYON_OT_add_teapot,
           HALCYON_OT_add_teaset,
           HALCYON_OT_add_cornell_box, HALCYON_OT_add_checker_plane,
           HALCYON_OT_add_terrain, HALCYON_OT_add_fur_shells,
           HALCYON_OT_fur_rebuild, HALCYON_PT_fur,
           VIEW3D_MT_halcyon_add)


def register():
    for cls in CLASSES:
        bpy.utils.register_class(cls)
    # the pelt's live dials live on the OBJECT (R211)
    bpy.types.Object.halcyon_fur = PointerProperty(type=HalcyonFurSettings)
    menu = getattr(bpy.types, 'VIEW3D_MT_add', None)
    if menu is not None and hasattr(menu, 'append'):
        menu.append(draw_add_menu)


def unregister():
    menu = getattr(bpy.types, 'VIEW3D_MT_add', None)
    if menu is not None and hasattr(menu, 'remove'):
        try:
            menu.remove(draw_add_menu)
        except Exception:                                       # noqa: BLE001
            pass
    try:
        del bpy.types.Object.halcyon_fur
    except Exception:                                           # noqa: BLE001
        pass
    for cls in reversed(CLASSES):
        try:
            bpy.utils.unregister_class(cls)
        except Exception:                                       # noqa: BLE001
            pass
