"""The period objects, in the 3D view's Add menu.

Every renderer of the era shipped with the same handful of things to point a
camera at, and comparing your output against somebody else's meant rendering
the same one. They are here under *Add > Halcyon*, generated by `core/geometry`
and arriving with Halcyon materials already on them, so that the first thing a
new user does can be pressing F12 rather than modelling.

The geometry is bpy-free and tested headlessly; this module is only the part
that cannot be -- meshes, materials, operators and the menu.
"""

import bpy
from bpy.props import (BoolProperty, EnumProperty, FloatProperty,
                       FloatVectorProperty, IntProperty)
from bpy.types import Menu, Operator

from . import templates
from .core import geometry as GEO

ENGINE = 'HALCYON_RENDER'


# ------------------------------------------------------------- scaffolding


def _material(name, color, model='PHONG', **inputs):
    """A Halcyon-shaded material, built rather than looked up.

    Named uniquely per object so adding two teapots does not have the second
    one silently repaint the first.
    """
    mat = bpy.data.materials.new(name)
    from . import compat
    compat.enable_nodes(mat)
    tree = mat.node_tree
    tree.nodes.clear()
    out = tree.nodes.new('ShaderNodeOutputMaterial')
    out.location = (320, 0)
    try:
        shader = tree.nodes.new('HALCYON_ShaderNode')
    except RuntimeError:
        # Halcyon's nodes are not registered -- fall back so the object still
        # arrives with something on it rather than the operator failing
        shader = tree.nodes.new('ShaderNodeBsdfDiffuse')
        shader.location = (0, 0)
        shader.inputs['Color'].default_value = tuple(color)
        tree.links.new(shader.outputs[0], out.inputs['Surface'])
        mat.diffuse_color = tuple(color)
        return mat
    shader.location = (0, 0)
    shader.model = model
    values = dict(inputs)
    values.setdefault('Diffuse Color', tuple(color))
    for key, value in values.items():
        sock = shader.inputs.get(key)
        if sock is None or not hasattr(sock, 'default_value'):
            continue
        try:
            if hasattr(sock.default_value, '__len__'):
                for i in range(min(len(sock.default_value), len(value))):
                    sock.default_value[i] = value[i]
            else:
                sock.default_value = float(value)
        except (TypeError, ValueError):
            pass
    shader.refresh_sockets()
    tree.links.new(shader.outputs['Surface'], out.inputs['Surface'])
    mat.diffuse_color = tuple(color)
    return mat


def _template_material(name, key, fallback):
    mat = bpy.data.materials.new(name)
    ok, _msg = templates.build(mat, key)
    if not ok:
        bpy.data.materials.remove(mat)
        return _material(name, fallback)
    return mat


def _new_object(context, name, verts, faces, materials=(), face_material=None,
                smooth=False, scale=1.0):
    """Build a mesh, wrap it in an object, and hand it to the user selected."""
    mesh = bpy.data.meshes.new(name)
    if scale != 1.0:
        verts = [(x * scale, y * scale, z * scale) for x, y, z in verts]
    mesh.from_pydata(list(verts), [], [list(f) for f in faces])
    mesh.update()
    for mat in materials:
        mesh.materials.append(mat)
    if face_material is not None and len(materials) > 1:
        for poly, index in zip(mesh.polygons, face_material):
            poly.material_index = index
    if smooth:
        for poly in mesh.polygons:
            poly.use_smooth = True

    ob = bpy.data.objects.new(name, mesh)
    collection = context.collection or context.scene.collection
    collection.objects.link(ob)
    cursor = getattr(getattr(context, 'scene', None), 'cursor', None)
    if cursor is not None:
        ob.location = tuple(cursor.location)
    for other in context.selected_objects:
        other.select_set(False)
    ob.select_set(True)
    context.view_layer.objects.active = ob
    return ob


class _AddBase(Operator):
    bl_options = {'REGISTER', 'UNDO'}

    @classmethod
    def poll(cls, context):
        return context.mode == 'OBJECT'


# ------------------------------------------------------------------ teapot


class HALCYON_OT_add_teapot(_AddBase):
    """The Utah teapot, swept from its profile at the resolution you ask for"""

    bl_idname = 'halcyon.add_teapot'
    bl_label = "Utah Teapot"

    steps: IntProperty(
        name="Steps", default=8, min=2, max=32,
        description="Subdivisions along the profile. The whole object is "
                    "generated, so this is a real resolution knob rather than "
                    "a decimation of something fixed")
    segments: IntProperty(name="Segments", default=16, min=4, max=64,
                          description="Subdivisions around the axis")
    size: FloatProperty(name="Size", default=0.5, min=0.001, max=100.0,
                        description="Scale. The teapot is 3.15 units tall "
                                    "before it, as Newell left it")
    smooth: BoolProperty(
        name="Shade Smooth", default=False,
        description="Off by default: faceted is what these looked like, and "
                    "Halcyon's Flat and Gouraud shading rates want the facets")
    material: EnumProperty(
        name="Material", default='CHROME',
        items=(('CHROME', "Chrome", "The one it was always rendered in"),
               ('GOLD', "Gold", ""), ('PLASTIC', "Shiny Plastic", ""),
               ('MARBLE', "Polished Marble", ""), ('NONE', "None", "")))

    def execute(self, context):
        verts, faces = GEO.utah_teapot(self.steps, self.segments)
        mats = ()
        if self.material != 'NONE':
            mats = (_template_material("Teapot", self.material,
                                       (0.75, 0.75, 0.78, 1.0)),)
        _new_object(context, "Teapot", verts, faces, mats,
                    smooth=self.smooth, scale=self.size)
        return {'FINISHED'}


class HALCYON_OT_add_teaset(_AddBase):
    """The rest of Newell's tea service: teapot, cup, saucer and spoon"""

    bl_idname = 'halcyon.add_teaset'
    bl_label = "Newell Teaset"

    steps: IntProperty(name="Steps", default=8, min=2, max=32)
    segments: IntProperty(name="Segments", default=16, min=4, max=64)
    size: FloatProperty(name="Size", default=0.35, min=0.001, max=100.0)
    smooth: BoolProperty(name="Shade Smooth", default=False)

    def execute(self, context):
        china = _material("Teaset China", (0.93, 0.92, 0.90, 1.0),
                          model='BLINN_PHONG', **{'Specular Level': 0.75,
                                                  'Glossiness': 90.0,
                                                  'Fresnel': 0.4})
        builders = {
            'teapot': lambda: GEO.utah_teapot(self.steps, self.segments),
            'teacup': lambda: GEO.teacup(max(self.steps - 2, 2), self.segments),
            'saucer': lambda: GEO.saucer(max(self.steps - 3, 2), self.segments),
            'teaspoon': lambda: GEO.teaspoon(max(self.steps - 2, 2),
                                             max(self.segments // 2, 4)),
        }
        made = []
        for label, key, offset, rel in GEO.TEASET_LAYOUT:
            verts, faces = builders[key]()
            ox, oy, oz = offset
            verts = [(x * rel + ox, y * rel + oy, z * rel + oz)
                     for x, y, z in verts]
            made.append(_new_object(context, label, verts, faces, (china,),
                                    smooth=self.smooth, scale=self.size))
        for ob in made:
            ob.select_set(True)
        if made:
            context.view_layer.objects.active = made[0]
        self.report({'INFO'}, f'{len(made)} objects added')
        return {'FINISHED'}


# ------------------------------------------------------------ Cornell box


class HALCYON_OT_add_cornell_box(_AddBase):
    """The Cornell box at its published dimensions, walls and blocks and all"""

    bl_idname = 'halcyon.add_cornell_box'
    bl_label = "Cornell Box"

    size: FloatProperty(
        name="Size", default=4.0, min=0.01, max=1000.0,
        description="Width of the box. The published measurements are in "
                    "millimetres and are scaled to this")
    emissive: BoolProperty(
        name="Emissive Light Panel", default=True,
        description="Give the ceiling panel a Constant white material. Halcyon "
                    "has no bounce light, so this lights nothing on its own -- "
                    "add an area lamp under it")
    add_lamp: BoolProperty(
        name="Add Area Lamp", default=True,
        description="Put an area lamp at the panel, sized and placed to match "
                    "it, so the box is lit the moment it is added")

    def execute(self, context):
        verts, faces, groups = GEO.cornell_box()
        palette = (
            ('white', (0.73, 0.73, 0.73, 1.0), 'LAMBERT', {}),
            ('red', (0.63, 0.06, 0.05, 1.0), 'LAMBERT', {}),
            ('green', (0.14, 0.45, 0.09, 1.0), 'LAMBERT', {}),
            ('light', (1.0, 0.95, 0.85, 1.0),
             'CONSTANT' if self.emissive else 'LAMBERT',
             {'Self-Illumination': (1.0, 0.95, 0.85, 1.0)}
             if self.emissive else {}),
            ('short', (0.73, 0.73, 0.73, 1.0), 'LAMBERT', {}),
            ('tall', (0.73, 0.73, 0.73, 1.0), 'LAMBERT', {}),
        )
        mats, index = [], {}
        for name, color, model, extra in palette:
            index[name] = len(mats)
            mats.append(_material(f'Cornell {name.title()}', color,
                                  model=model, **extra))
        ob = _new_object(context, "Cornell Box", verts, faces, mats,
                         [index[g] for g in groups], scale=self.size)

        if self.add_lamp:
            lamp_data = bpy.data.lights.new("Cornell Light", 'AREA')
            lamp_data.energy = 100.0 * max(self.size, 0.01) ** 2
            lamp_data.color = (1.0, 0.95, 0.85)
            try:
                lamp_data.shape = 'RECTANGLE'
                lamp_data.size = 0.235 * self.size
                lamp_data.size_y = 0.19 * self.size
            except (AttributeError, TypeError):
                pass
            lamp = bpy.data.objects.new("Cornell Light", lamp_data)
            (context.collection or context.scene.collection).objects.link(lamp)
            # the panel sits at 548.7/552.8 of the box width, just under the
            # ceiling, and the lamp goes a hair below it so it is not co-planar
            lamp.location = (ob.location[0] + 0.0,
                             ob.location[1] + 0.0,
                             ob.location[2] + 0.986 * self.size)
            lamp.rotation_euler = (3.14159265, 0.0, 0.0)
            lamp.parent = ob
            lamp.matrix_parent_inverse = ob.matrix_world.inverted()
        return {'FINISHED'}


# ------------------------------------------------------------ checkerboard


class HALCYON_OT_add_checker_plane(_AddBase):
    """A checkerboard as real alternating faces, not a texture"""

    bl_idname = 'halcyon.add_checker_plane'
    bl_label = "Checker Ground Plane"

    size: FloatProperty(name="Size", default=20.0, min=0.01, max=10000.0)
    divisions: IntProperty(name="Divisions", default=8, min=1, max=256,
                           description="Squares across")
    color_a: FloatVectorProperty(name="Colour A", subtype='COLOR', size=4,
                                 min=0.0, max=1.0,
                                 default=(0.9, 0.9, 0.9, 1.0))
    color_b: FloatVectorProperty(name="Colour B", subtype='COLOR', size=4,
                                 min=0.0, max=1.0,
                                 default=(0.06, 0.06, 0.07, 1.0))
    glossy: BoolProperty(
        name="Reflective", default=False,
        description="Add a reflection amount, for the ray-traced chequerboard "
                    "every renderer's first demo image stood on")

    def execute(self, context):
        verts, faces, groups = GEO.checker_plane(self.size, self.divisions)
        extra = {'Reflection': 0.35, 'Specular Level': 0.7,
                 'Glossiness': 180.0} if self.glossy else {}
        mats = (_material("Checker A", tuple(self.color_a), **extra),
                _material("Checker B", tuple(self.color_b), **extra))
        _new_object(context, "Checker Plane", verts, faces, mats, groups)
        return {'FINISHED'}


# ----------------------------------------------------------- the terrain


def _terrain_material(name, height):
    """R201: the Bryce terrain material, wired to Altitude & Slope.

    The node shipped in an earlier round with nothing to stand on; the
    Terrain operator is what it was built to paint. Factor (height,
    normalised 0..Maximum) drives a colour ramp -- shore grass up
    through rock to snow -- and Slope pulls steep faces toward bare
    rock through a Mix, so cliffs stay stone whatever their altitude.
    All standard nodes plus the two Halcyon ones, fully editable
    afterwards, and the whole chain evaluates identically on the CPU
    and the GPU simulator (both roads already speak every node here).
    """
    mat = bpy.data.materials.new(name)
    from . import compat
    compat.enable_nodes(mat)
    tree = mat.node_tree
    tree.nodes.clear()
    out = tree.nodes.new('ShaderNodeOutputMaterial')
    out.location = (720, 0)
    try:
        shader = tree.nodes.new('HALCYON_ShaderNode')
        alt = tree.nodes.new('HALCYON_AltitudeSlopeNode')
    except RuntimeError:
        # engine nodes unregistered -- a plain matte stand-in so the
        # operator still delivers a mountain rather than an error
        shader = tree.nodes.new('ShaderNodeBsdfDiffuse')
        shader.inputs['Color'].default_value = (0.35, 0.32, 0.28, 1.0)
        tree.links.new(shader.outputs[0], out.inputs['Surface'])
        mat.diffuse_color = (0.35, 0.32, 0.28, 1.0)
        return mat
    shader.location = (480, 0)
    shader.model = 'LAMBERT'
    alt.location = (-260, 0)
    for nm, val in (('Minimum', 0.0), ('Maximum', float(height))):
        s = alt.inputs.get(nm)
        if s is not None:
            s.default_value = val
    ramp = tree.nodes.new('ShaderNodeValToRGB')
    ramp.location = (0, 120)
    cr = ramp.color_ramp
    # four stops: shore grass, dry scrub, bare rock, snowcap
    stops = ((0.0, (0.20, 0.28, 0.12, 1.0)),
             (0.35, (0.36, 0.30, 0.20, 1.0)),
             (0.62, (0.38, 0.36, 0.34, 1.0)),
             (0.85, (0.92, 0.94, 0.97, 1.0)))
    while len(cr.elements) > 1:
        cr.elements.remove(cr.elements[-1])
    cr.elements[0].position = stops[0][0]
    cr.elements[0].color = stops[0][1]
    for pos, col in stops[1:]:
        el = cr.elements.new(pos)
        el.color = col
    mix = tree.nodes.new('ShaderNodeMix')
    mix.location = (260, 40)
    try:
        mix.data_type = 'RGBA'
        mix.clamp_factor = True
    except AttributeError:
        pass

    def _mix_in(nm, ty):
        for s in mix.inputs:
            if s.name == nm and (ty is None or s.type == ty):
                return s
        return None

    rock = _mix_in('B', 'RGBA')
    if rock is not None:
        rock.default_value = (0.33, 0.31, 0.30, 1.0)
    tree.links.new(alt.outputs['Factor'], ramp.inputs['Fac'])
    a_in = _mix_in('A', 'RGBA')
    if a_in is not None:
        tree.links.new(ramp.outputs['Color'], a_in)
    f_in = _mix_in('Factor', 'VALUE')
    if f_in is not None:
        tree.links.new(alt.outputs['Slope'], f_in)
    dc = shader.inputs.get('Diffuse Color')
    if dc is not None:
        res = None
        for s in mix.outputs:
            if s.name == 'Result' and s.type == 'RGBA':
                res = s
                break
        tree.links.new(res if res is not None
                       else mix.outputs[0], dc)
    sl = shader.inputs.get('Specular Level')
    if sl is not None and hasattr(sl, 'default_value'):
        sl.default_value = 0.05
    shader.refresh_sockets()
    tree.links.new(shader.outputs['Surface'], out.inputs['Surface'])
    mat.diffuse_color = (0.38, 0.36, 0.34, 1.0)
    return mat


class HALCYON_OT_add_terrain(_AddBase):
    """A fractal mountain with the Bryce material already on it --
    altitude bands from shore to snow, steep faces pulled to rock"""

    bl_idname = 'halcyon.add_terrain'
    bl_label = "Terrain"

    kind: EnumProperty(
        name="Type", default='MOUNTAIN',
        description="The landform this terrain grows into; every type "
                    "still takes the island, terrace and sea dials",
        items=[
            ('MOUNTAIN', "Mountain",
             "The fractal peak -- rolling fBm blended toward ridged "
             "crests by the Ridged dial"),
            ('HILLS', "Rolling Hills",
             "Soft pastureland, no crests at all"),
            ('CANYON', "Canyon",
             "A high mesa with winding channels carved out of it"),
            ('DUNES', "Dunes",
             "Directional sand waves; the Direction dial turns the "
             "wind that laid them"),
            ('CRATER', "Crater",
             "One great ringed impact: raised rim, sunken floor"),
            ('VOLCANO', "Volcano",
             "The cone with its caldera bitten out of the top"),
            ('PLATEAU', "Plateau",
             "Hard-shouldered table-land, flat on top"),
        ])
    direction: FloatProperty(
        name="Direction", default=0.0, min=-6.2832, max=6.2832,
        subtype='ANGLE',
        description="Turns the Dunes' wind (and is free for any kind "
                    "that later wants a bearing)")
    size: FloatProperty(
        name="Size", default=24.0, min=0.1, max=10000.0,
        description="Width of the terrain grid in scene units")
    divisions: IntProperty(
        name="Divisions", default=96, min=2, max=512,
        description="Grid squares along each side; 96 is a Bryce-era "
                    "mountain, 256 a modern one")
    height: FloatProperty(
        name="Height", default=6.0, min=0.0, max=1000.0,
        description="Peak altitude of the fractal at full strength")
    feature_scale: FloatProperty(
        name="Feature Scale", default=10.0, min=0.1, max=1000.0,
        description="Metres per large noise feature -- bigger numbers "
                    "mean broader, calmer mountains")
    octaves: IntProperty(
        name="Detail", default=6, min=1, max=12,
        description="Fractal detail levels; each adds finer bumps at "
                    "half the strength set by Roughness")
    roughness: FloatProperty(
        name="Roughness", default=0.5, min=0.05, max=0.95,
        description="How much each finer detail level contributes -- "
                    "low is rolling hills, high is crumpled rock")
    ridge: FloatProperty(
        name="Ridged", default=0.5, min=0.0, max=1.0,
        description="Blend from smooth rolling fBm (0) to the "
                    "knife-edged ridged crests Bryce is remembered "
                    "for (1)")
    island: FloatProperty(
        name="Island Falloff", default=0.4, min=0.0, max=1.0,
        description="Fades the height to zero toward the grid edge so "
                    "the mountain ends inside the grid instead of "
                    "slicing off at the boundary; 0 disables")
    terraces: IntProperty(
        name="Terraces", default=0, min=0, max=64,
        description="Above zero, quantises the height into this many "
                    "shelves with smoothed risers -- Bryce's "
                    "terracing; 0 is off")
    sea_level: FloatProperty(
        name="Sea Level", default=0.0, min=0.0, max=0.95,
        description="Flattens everything below this fraction of the "
                    "height into a floor -- the water table an ocean "
                    "plane sits on; 0 is off")
    seed: IntProperty(
        name="Seed", default=0, min=0, max=100000,
        description="Re-deals the mountain; the same seed builds the "
                    "same mountain on every machine")
    smooth: BoolProperty(
        name="Smooth Shading", default=True,
        description="Smooth-shade the grid so slopes grade instead of "
                    "facet; turn off for the flat-shaded early look")

    def execute(self, context):
        verts, faces = GEO.terrain(
            self.size, self.divisions, self.height, self.feature_scale,
            self.octaves, self.roughness, self.ridge, self.island,
            self.terraces, self.sea_level, self.seed,
            kind=self.kind, direction=self.direction)
        label = self.kind.title().replace('_', ' ')
        mat = _terrain_material(label, max(float(self.height), 1e-3))
        _new_object(context, label, verts, faces, (mat,),
                    smooth=self.smooth)
        return {'FINISHED'}


# -------------------------------------------------------------- the menu


class VIEW3D_MT_halcyon_add(Menu):
    bl_idname = 'VIEW3D_MT_halcyon_add'
    bl_label = "Halcyon"

    def draw(self, context):
        layout = self.layout
        layout.operator(HALCYON_OT_add_teapot.bl_idname, icon='MESH_MONKEY')
        layout.operator(HALCYON_OT_add_teaset.bl_idname, icon='OUTLINER_OB_MESH')
        layout.separator()
        layout.operator(HALCYON_OT_add_cornell_box.bl_idname, icon='MESH_CUBE')
        layout.operator(HALCYON_OT_add_checker_plane.bl_idname,
                        icon='MESH_GRID')
        layout.separator()
        layout.operator(HALCYON_OT_add_terrain.bl_idname,
                        icon='RNDCURVE')


def draw_add_menu(self, context):
    if getattr(context, 'engine', None) != ENGINE:
        return
    self.layout.separator()
    self.layout.menu(VIEW3D_MT_halcyon_add.bl_idname, icon='SHADING_RENDERED')


CLASSES = (HALCYON_OT_add_teapot, HALCYON_OT_add_teaset,
           HALCYON_OT_add_cornell_box, HALCYON_OT_add_checker_plane,
           HALCYON_OT_add_terrain, VIEW3D_MT_halcyon_add)


def register():
    for cls in CLASSES:
        bpy.utils.register_class(cls)
    menu = getattr(bpy.types, 'VIEW3D_MT_add', None)
    if menu is not None and hasattr(menu, 'append'):
        menu.append(draw_add_menu)


def unregister():
    menu = getattr(bpy.types, 'VIEW3D_MT_add', None)
    if menu is not None and hasattr(menu, 'remove'):
        try:
            menu.remove(draw_add_menu)
        except Exception:                                       # noqa: BLE001
            pass
    for cls in reversed(CLASSES):
        try:
            bpy.utils.unregister_class(cls)
        except Exception:                                       # noqa: BLE001
            pass
