"""The period objects, in the 3D view's Add menu.

Every renderer of the era shipped with the same handful of things to point a
camera at, and comparing your output against somebody else's meant rendering
the same one. They are here under *Add > Halcyon*, generated by `core/geometry`
and arriving with Halcyon materials already on them, so that the first thing a
new user does can be pressing F12 rather than modelling.

The geometry is bpy-free and tested headlessly; this module is only the part
that cannot be -- meshes, materials, operators and the menu.
"""

import bpy
from bpy.props import (BoolProperty, EnumProperty, FloatProperty,
                       FloatVectorProperty, IntProperty)
from bpy.types import Menu, Operator

from . import templates
from .core import geometry as GEO

ENGINE = 'HALCYON_RENDER'


# ------------------------------------------------------------- scaffolding


def _material(name, color, model='PHONG', **inputs):
    """A Halcyon-shaded material, built rather than looked up.

    Named uniquely per object so adding two teapots does not have the second
    one silently repaint the first.
    """
    mat = bpy.data.materials.new(name)
    from . import compat
    compat.enable_nodes(mat)
    tree = mat.node_tree
    tree.nodes.clear()
    out = tree.nodes.new('ShaderNodeOutputMaterial')
    out.location = (320, 0)
    try:
        shader = tree.nodes.new('HALCYON_ShaderNode')
    except RuntimeError:
        # Halcyon's nodes are not registered -- fall back so the object still
        # arrives with something on it rather than the operator failing
        shader = tree.nodes.new('ShaderNodeBsdfDiffuse')
        shader.location = (0, 0)
        shader.inputs['Color'].default_value = tuple(color)
        tree.links.new(shader.outputs[0], out.inputs['Surface'])
        mat.diffuse_color = tuple(color)
        return mat
    shader.location = (0, 0)
    shader.model = model
    values = dict(inputs)
    values.setdefault('Diffuse Color', tuple(color))
    for key, value in values.items():
        sock = shader.inputs.get(key)
        if sock is None or not hasattr(sock, 'default_value'):
            continue
        try:
            if hasattr(sock.default_value, '__len__'):
                for i in range(min(len(sock.default_value), len(value))):
                    sock.default_value[i] = value[i]
            else:
                sock.default_value = float(value)
        except (TypeError, ValueError):
            pass
    shader.refresh_sockets()
    tree.links.new(shader.outputs['Surface'], out.inputs['Surface'])
    mat.diffuse_color = tuple(color)
    return mat


def _template_material(name, key, fallback):
    mat = bpy.data.materials.new(name)
    ok, _msg = templates.build(mat, key)
    if not ok:
        bpy.data.materials.remove(mat)
        return _material(name, fallback)
    return mat


def _new_object(context, name, verts, faces, materials=(), face_material=None,
                smooth=False, scale=1.0):
    """Build a mesh, wrap it in an object, and hand it to the user selected."""
    mesh = bpy.data.meshes.new(name)
    if scale != 1.0:
        verts = [(x * scale, y * scale, z * scale) for x, y, z in verts]
    mesh.from_pydata(list(verts), [], [list(f) for f in faces])
    mesh.update()
    for mat in materials:
        mesh.materials.append(mat)
    if face_material is not None and len(materials) > 1:
        for poly, index in zip(mesh.polygons, face_material):
            poly.material_index = index
    if smooth:
        for poly in mesh.polygons:
            poly.use_smooth = True

    ob = bpy.data.objects.new(name, mesh)
    collection = context.collection or context.scene.collection
    collection.objects.link(ob)
    cursor = getattr(getattr(context, 'scene', None), 'cursor', None)
    if cursor is not None:
        ob.location = tuple(cursor.location)
    for other in context.selected_objects:
        other.select_set(False)
    ob.select_set(True)
    context.view_layer.objects.active = ob
    return ob


class _AddBase(Operator):
    bl_options = {'REGISTER', 'UNDO'}

    @classmethod
    def poll(cls, context):
        return context.mode == 'OBJECT'


# ------------------------------------------------------------------ teapot


class HALCYON_OT_add_teapot(_AddBase):
    """The Utah teapot, swept from its profile at the resolution you ask for"""

    bl_idname = 'halcyon.add_teapot'
    bl_label = "Utah Teapot"

    steps: IntProperty(
        name="Steps", default=8, min=2, max=32,
        description="Subdivisions along the profile. The whole object is "
                    "generated, so this is a real resolution knob rather than "
                    "a decimation of something fixed")
    segments: IntProperty(name="Segments", default=16, min=4, max=64,
                          description="Subdivisions around the axis")
    size: FloatProperty(name="Size", default=0.5, min=0.001, max=100.0,
                        description="Scale. The teapot is 3.15 units tall "
                                    "before it, as Newell left it")
    smooth: BoolProperty(
        name="Shade Smooth", default=False,
        description="Off by default: faceted is what these looked like, and "
                    "Halcyon's Flat and Gouraud shading rates want the facets")
    material: EnumProperty(
        name="Material", default='CHROME',
        items=(('CHROME', "Chrome", "The one it was always rendered in"),
               ('GOLD', "Gold", ""), ('PLASTIC', "Shiny Plastic", ""),
               ('MARBLE', "Polished Marble", ""), ('NONE', "None", "")))

    def execute(self, context):
        verts, faces = GEO.utah_teapot(self.steps, self.segments)
        mats = ()
        if self.material != 'NONE':
            mats = (_template_material("Teapot", self.material,
                                       (0.75, 0.75, 0.78, 1.0)),)
        _new_object(context, "Teapot", verts, faces, mats,
                    smooth=self.smooth, scale=self.size)
        return {'FINISHED'}


class HALCYON_OT_add_teaset(_AddBase):
    """The rest of Newell's tea service: teapot, cup, saucer and spoon"""

    bl_idname = 'halcyon.add_teaset'
    bl_label = "Newell Teaset"

    steps: IntProperty(name="Steps", default=8, min=2, max=32)
    segments: IntProperty(name="Segments", default=16, min=4, max=64)
    size: FloatProperty(name="Size", default=0.35, min=0.001, max=100.0)
    smooth: BoolProperty(name="Shade Smooth", default=False)

    def execute(self, context):
        china = _material("Teaset China", (0.93, 0.92, 0.90, 1.0),
                          model='BLINN_PHONG', **{'Specular Level': 0.75,
                                                  'Glossiness': 90.0,
                                                  'Fresnel': 0.4})
        builders = {
            'teapot': lambda: GEO.utah_teapot(self.steps, self.segments),
            'teacup': lambda: GEO.teacup(max(self.steps - 2, 2), self.segments),
            'saucer': lambda: GEO.saucer(max(self.steps - 3, 2), self.segments),
            'teaspoon': lambda: GEO.teaspoon(max(self.steps - 2, 2),
                                             max(self.segments // 2, 4)),
        }
        made = []
        for label, key, offset, rel in GEO.TEASET_LAYOUT:
            verts, faces = builders[key]()
            ox, oy, oz = offset
            verts = [(x * rel + ox, y * rel + oy, z * rel + oz)
                     for x, y, z in verts]
            made.append(_new_object(context, label, verts, faces, (china,),
                                    smooth=self.smooth, scale=self.size))
        for ob in made:
            ob.select_set(True)
        if made:
            context.view_layer.objects.active = made[0]
        self.report({'INFO'}, f'{len(made)} objects added')
        return {'FINISHED'}


# ------------------------------------------------------------ Cornell box


class HALCYON_OT_add_cornell_box(_AddBase):
    """The Cornell box at its published dimensions, walls and blocks and all"""

    bl_idname = 'halcyon.add_cornell_box'
    bl_label = "Cornell Box"

    size: FloatProperty(
        name="Size", default=4.0, min=0.01, max=1000.0,
        description="Width of the box. The published measurements are in "
                    "millimetres and are scaled to this")
    emissive: BoolProperty(
        name="Emissive Light Panel", default=True,
        description="Give the ceiling panel a Constant white material. Halcyon "
                    "has no bounce light, so this lights nothing on its own -- "
                    "add an area lamp under it")
    add_lamp: BoolProperty(
        name="Add Area Lamp", default=True,
        description="Put an area lamp at the panel, sized and placed to match "
                    "it, so the box is lit the moment it is added")

    def execute(self, context):
        verts, faces, groups = GEO.cornell_box()
        palette = (
            ('white', (0.73, 0.73, 0.73, 1.0), 'LAMBERT', {}),
            ('red', (0.63, 0.06, 0.05, 1.0), 'LAMBERT', {}),
            ('green', (0.14, 0.45, 0.09, 1.0), 'LAMBERT', {}),
            ('light', (1.0, 0.95, 0.85, 1.0),
             'CONSTANT' if self.emissive else 'LAMBERT',
             {'Self-Illumination': (1.0, 0.95, 0.85, 1.0)}
             if self.emissive else {}),
            ('short', (0.73, 0.73, 0.73, 1.0), 'LAMBERT', {}),
            ('tall', (0.73, 0.73, 0.73, 1.0), 'LAMBERT', {}),
        )
        mats, index = [], {}
        for name, color, model, extra in palette:
            index[name] = len(mats)
            mats.append(_material(f'Cornell {name.title()}', color,
                                  model=model, **extra))
        ob = _new_object(context, "Cornell Box", verts, faces, mats,
                         [index[g] for g in groups], scale=self.size)

        if self.add_lamp:
            lamp_data = bpy.data.lights.new("Cornell Light", 'AREA')
            lamp_data.energy = 100.0 * max(self.size, 0.01) ** 2
            lamp_data.color = (1.0, 0.95, 0.85)
            try:
                lamp_data.shape = 'RECTANGLE'
                lamp_data.size = 0.235 * self.size
                lamp_data.size_y = 0.19 * self.size
            except (AttributeError, TypeError):
                pass
            lamp = bpy.data.objects.new("Cornell Light", lamp_data)
            (context.collection or context.scene.collection).objects.link(lamp)
            # the panel sits at 548.7/552.8 of the box width, just under the
            # ceiling, and the lamp goes a hair below it so it is not co-planar
            lamp.location = (ob.location[0] + 0.0,
                             ob.location[1] + 0.0,
                             ob.location[2] + 0.986 * self.size)
            lamp.rotation_euler = (3.14159265, 0.0, 0.0)
            lamp.parent = ob
            lamp.matrix_parent_inverse = ob.matrix_world.inverted()
        return {'FINISHED'}


# ------------------------------------------------------------ checkerboard


class HALCYON_OT_add_checker_plane(_AddBase):
    """A checkerboard as real alternating faces, not a texture"""

    bl_idname = 'halcyon.add_checker_plane'
    bl_label = "Checker Ground Plane"

    size: FloatProperty(name="Size", default=20.0, min=0.01, max=10000.0)
    divisions: IntProperty(name="Divisions", default=8, min=1, max=256,
                           description="Squares across")
    color_a: FloatVectorProperty(name="Colour A", subtype='COLOR', size=4,
                                 min=0.0, max=1.0,
                                 default=(0.9, 0.9, 0.9, 1.0))
    color_b: FloatVectorProperty(name="Colour B", subtype='COLOR', size=4,
                                 min=0.0, max=1.0,
                                 default=(0.06, 0.06, 0.07, 1.0))
    glossy: BoolProperty(
        name="Reflective", default=False,
        description="Add a reflection amount, for the ray-traced chequerboard "
                    "every renderer's first demo image stood on")

    def execute(self, context):
        verts, faces, groups = GEO.checker_plane(self.size, self.divisions)
        extra = {'Reflection': 0.35, 'Specular Level': 0.7,
                 'Glossiness': 180.0} if self.glossy else {}
        mats = (_material("Checker A", tuple(self.color_a), **extra),
                _material("Checker B", tuple(self.color_b), **extra))
        _new_object(context, "Checker Plane", verts, faces, mats, groups)
        return {'FINISHED'}


# -------------------------------------------------------------- the menu


class VIEW3D_MT_halcyon_add(Menu):
    bl_idname = 'VIEW3D_MT_halcyon_add'
    bl_label = "Halcyon"

    def draw(self, context):
        layout = self.layout
        layout.operator(HALCYON_OT_add_teapot.bl_idname, icon='MESH_MONKEY')
        layout.operator(HALCYON_OT_add_teaset.bl_idname, icon='OUTLINER_OB_MESH')
        layout.separator()
        layout.operator(HALCYON_OT_add_cornell_box.bl_idname, icon='MESH_CUBE')
        layout.operator(HALCYON_OT_add_checker_plane.bl_idname,
                        icon='MESH_GRID')


def draw_add_menu(self, context):
    if getattr(context, 'engine', None) != ENGINE:
        return
    self.layout.separator()
    self.layout.menu(VIEW3D_MT_halcyon_add.bl_idname, icon='SHADING_RENDERED')


CLASSES = (HALCYON_OT_add_teapot, HALCYON_OT_add_teaset,
           HALCYON_OT_add_cornell_box, HALCYON_OT_add_checker_plane,
           VIEW3D_MT_halcyon_add)


def register():
    for cls in CLASSES:
        bpy.utils.register_class(cls)
    menu = getattr(bpy.types, 'VIEW3D_MT_add', None)
    if menu is not None and hasattr(menu, 'append'):
        menu.append(draw_add_menu)


def unregister():
    menu = getattr(bpy.types, 'VIEW3D_MT_add', None)
    if menu is not None and hasattr(menu, 'remove'):
        try:
            menu.remove(draw_add_menu)
        except Exception:                                       # noqa: BLE001
            pass
    for cls in reversed(CLASSES):
        try:
            bpy.utils.unregister_class(cls)
        except Exception:                                       # noqa: BLE001
            pass
